-- -----------------------------------------------------
-- Insercion de Datos
-- -----------------------------------------------------

USE LabRem_Control;

-- -----------------------------------------------------
-- Laboratorios
-- -----------------------------------------------------

INSERT INTO Laboratorios VALUES (DEFAULT,DEFAULT,'Submuestreo, aliasing y efecto estroboscópico',NULL,'Esta experiencia tiene como objetivo ayudar a que los estudiantes comprendan, mediante un experimento visual, los efectos del submuestreo, el fenómeno de aliasing y el principio de funcionamiento de los osciloscopios de submuestreo y de técnicas que emplean iluminación estroboscópica. El experimento consiste en la observación de una delgada caída de agua, que oscila lateralmente a una frecuencia variable a voluntad. El agua es iluminada con una luz estroboscópica, cuyo valor de frecuencia se fija en las cercanías del valor de la frecuencia de oscilación de la corriente de agua o submúltiplos de la misma. Debido a la fuerza de gravedad, la corriente de agua se va separando en múltiples gotitas. Gracias a la retención de imágenes en la retina, y según sea la diferencia de valores entre las dos frecuencias empleadas, se logra la ilusión óptica de percibir a las gotas de agua descendiendo o ascendiendo a velocidades notablemente inferiores a las de caída libre. Estos mismos efectos pueden observarse empleando una cámara de video digital en lugar de la lámpara estroboscópica. Los datos de entrada necesarios para la experiencia son las frecuencias de oscilación de la corriente de agua y de la lámpara estroboscópica, además del inicio/detención del flujo de agua. El resultado cuantitativo del experimento es la frecuencia de oscilación aparente de la corriente de agua, que debe ser calculada por los alumnos a partir del cronometraje del movimiento. Para esta experiencia actualmente se dispone de: a) un circuito generador de pulsos más lámpara led de 3W, b) Un circuito generador de onda cuadrada, más un actuador apropiado para mover lateralmente la corriente de agua y c) Sistema de bombeo y recolección de agua. Los resultados experimentales se comparan con gráficas y simulaciones realizadas con el software Octave (que no necesita licencia).');
INSERT INTO Laboratorios VALUES (DEFAULT,DEFAULT,'Sistema de control automático de posición',NULL,'Con esta experiencia se busca que los estudiantes puedan percibir de manera visual el comportamiento genérico de un sistema de control así como el efecto de las distintas estrategias de control que pueden usarse. Se busca desarrollar competencias en la identificación de plantas y en el diseño de controladores. Se cuenta con un motor eléctrico y un tren reductor, siendo la variable a controlar la posición angular del eje de salida. Esta variable y su rapidez de cambio se digitalizan para usarse como variables de feedback. A la electrónica del driver del motor pueden agregarse (por software) modificaciones como retardos, no linealidades o polos-ceros extras; pudiendo emularse el funcionamiento de distintas plantas de control. El controlador también es configurable por software y recibe las señales temporales de referencia y de feedback. Las experiencias realizadas son de dos tipos: IDENTIFICACIÓN: los parámetros del actuador son conocidos por el docente pero no por los alumnos; estos deberán inferir un modelo de la planta a partir de los datos de entrada y salida. TESTEO: sobre una planta, especificaciones dadas, y estrategia de control propuesta por el alumno, se comprueba la efectividad del sistema de control diseñado. Los datos de entrada son las señales temporales aplicadas como referencia del sistema de control; además, se deben cargar los parámetros que modifican al driver, así como los correspondientes al controlador propuesto. Las variables físicas a medir (en formato amplitud-tiempo) son la posición y la velocidad angular del eje de salida. Para desarrollar esta experiencia actualmente se dispone de: a) Conjunto motor-reductor b) Actuador configurable y c) Controlador configurable. Se emplea el software Octave, los entornos de programación para Arduino y software de desarrollo propio. No requieren licencia.');

-- -----------------------------------------------------
-- Ensayos
-- -----------------------------------------------------

-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"rangoAzimut": 40, "rangoElevacion": 25}', '{"rangoAzimut": 40, "rangoElevacion": 15}',1);


-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "4-QAM", "tipoCodificacion": 1, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 1, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 1, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 2, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "8-QAM", "tipoCodificacion": 2, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 4, DEFAULT, '{"tipoModulacion": "16-QAM", "tipoCodificacion": 2, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 2, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 2, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 3, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 2, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 3, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "PSK", "tipoCodificacion": 3, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 10, "intensidadMax": 50 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 1, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 15, "intensidadMax": 80 }', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 20, "intensidadMax": 100}', '{"intensidad": 40, "tasaError": 0.4}',2);
-- INSERT INTO Ensayos (idEnsayo, idUsuario, fechaHora, datosEntrada, datosSalida, idLaboratorio) VALUES (DEFAULT, 5, DEFAULT, '{"tipoModulacion": "FSK", "tipoCodificacion": 3, "intensidadMin": 25, "intensidadMax": 120}', '{"intensidad": 40, "tasaError": 0.4}',2);